#!/bin/bash

REGEX_TASK_ID="someRandom-[0-9]+"
TASK_ID_IN_COMMIT=$(echo $(cat "$1") | grep -o -E "$REGEX_TASK_ID")

MSG="$1"
TASK = $(echo $(git rev-parse --abbrev-ref HEAD) | grep -o -E)

if [[ -z "$TASK_ID_IN_COMMIT" ]]; then
    BRANCH_NAME=$(git symbolic-ref --short HEAD)
    TASK_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_TASK_ID")

    echo "$TASK_ID $(cat "$1")" > "$1"
fi
